print("list[:]             >> All")
print("list[Low:]          >> Low to End")
print("list[:High]         >> Begining to High")
print("list[Low:High]      >> Low to High")
print("list[::Step]        >> Start to End with Step")
print("list[Low::Step]     >> Low to End with Step")
print("list[:High:Step]    >> Start to High with Step")
print("list[Low:High:Step] >> Low to High with Step")

# print("Simple")
# print("list[3]")
# print(list[3])
# print("list[-3]")
# print(list[-3])
# print("list[:]")
# print(list[:])
# print("list[3:]")
# print(list[3:])
# print("list[:3]")
# print(list[:3])
# print("list[-3:]")
# print(list[-3:])
# print("list[:-3]")
# print(list[:-3])
list = ["A", "B", "C", "D", "E", "F", "G", "H", "I"]
print(f"\n{list}\n")

# print("Double - 2 Digits")
# print("list[-12:1]")
# print(list[-12:1])
# print("list[-12:3]")
# print(list[-12:3])
# print("list[1:-8]")
# print(list[1:-8])
# print("list[1:-11]")
# print(list[1:-11])
# print("list[1:-6]")
# print(list[1:-6])
# print("list[2:6]")
# print(list[2:6])
# print("list[-2]")
# print(list[-2])

print("Double with Step")
print("list[2:7:4]")
print(list[2:7:4])
print("list[2:5:7]")
print(list[2:5:7])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])

# # More Variations
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])

# # More Variations
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
# print(list[:])
